In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a.shape

(3, 4)

In [6]:
a.ndim # or len(a.shape)

2

In [7]:
a.size

12

In [8]:
np.zeros((4,4,3,2)) #n dimensional array

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [9]:
type(np.zeros((4,4,4,4)))

numpy.ndarray

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.full((3,4), np.pi) #Creates an array of the given shape initialized with the given value. Here's a 3x4 matrix full of π.


array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [12]:
np.empty((3,4)) #An uninitialized 2x3 array (its content is not predictable, as it is whatever is in memory at that point):

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [13]:
np.array([[1,2,3], [3,4,5]]) #Of course you can initialize an `ndarray` using a regular python array. Just call the `array` function:

array([[1, 2, 3],
       [3, 4, 5]])

In [14]:
np.arange(3,4)
np.arange(1.0, 5.0)
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

However, when dealing with floats, the exact number of elements in the array is not always predictible. For example, consider this:



In [15]:
print(np.arange(0, 5/3, 1/3))   # # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.arange(0, 5/3, 0.333333333))
print(np.arange(0, 5/3, 0.333333334))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333334]


## `np.linspace`
For this reason, it is generally preferable to use the `linspace` function instead of `arange` when working with floats. The `linspace` function returns an array containing a specific number of points evenly distributed between two values (note that the maximum value is *included*, contrary to `arange`):

In [16]:
print(np.linspace(0, 5/3, 6))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [17]:
print(np.linspace(0, 5/3, 1/3))   # # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.linspace(0, 5/3, 0.333333333))
print(np.linspace(0, 5/3, 0.333333334))

[]
[]
[]


C:\Users\Sushil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  """Entry point for launching an IPython kernel.
C:\Users\Sushil\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  
C:\Users\Sushil\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  This is separate from the ipykernel package so we can avoid doing imports until


In [18]:
np.random.rand(3,4)

array([[0.30136554, 0.11627229, 0.15079703, 0.15398086],
       [0.1337719 , 0.36855432, 0.9166449 , 0.86305523],
       [0.52354999, 0.3625795 , 0.54792571, 0.30623065]])

In [19]:
np.random.randn(3,4)

array([[-1.26662735, -0.16561473,  0.19394204,  1.6172457 ],
       [-0.43131642, -1.77117147,  0.83730759, -0.84149453],
       [-0.55586426,  1.67441714,  0.35031095,  1.94484567]])

In [20]:
import matplotlib.pyplot as plt
%matplotlib.inline

UsageError: Line magic function `%matplotlib.inline` not found.


In [ ]:
plt.hist(np.random.rand(100000), normed=True, bins=100, histtype="step", color="blue", label="rand")
plt.hist(np.random.randn(100000), normed="True", bins=100, histtype="step", color="red", label="randn")
plt.axis([-2.5, 2.5, 0, 1.1])
plt.legend(loc="upper left")
plt.title("random destribution")
plt.xlabel("value")
plt.ylabel("density")
plt.show()

In [ ]:
def myfunction(z, y, x):   #initialize an array using fromfunction(function, (dimension, row, coloumn))
    return x * y + z
np.fromfunction(myfunction, (3, 2, 10))

In [ ]:
c = np.arange(1, 5)
print(c.dtype, c)

In [ ]:
d = np.arange(1, 5, dtype=np.complex64)
print(d.dtype, d)

In [ ]:
e = np.arange(1, 5, dtype=np.complex64)     #returns the size (in bytes) of each item:
e.itemsize

In [ ]:
a  = np.array([[1,2,3], [4,5,7]], dtype=np.int64)
a.data

In [ ]:
g = np.arange(24)
print(g)
print("rank", g.ndim)

In [ ]:
g.shape = (6, 4)
print(g)
print("rank :", g.ndim)

In [ ]:
g2 = g.reshape(4, 6)
g2

In [ ]:
g2[1, 2] = 999
g2

In [ ]:
g

In [ ]:
g.ravel()   #ravel() function return a one dimension array

In [ ]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b  =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

In [ ]:
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

In [ ]:
k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)
print(k2.dtype, k2)

In [ ]:
k3 = k2 + 1.5          #When trying to combine arrays with different dtypes,
print(k3.dtype, k3)    #NumPy will upcast to a type capable of handling all possible values 
                       #(regardless of what the actual values are).

In [ ]:
m = np.array([20, -5, 30, 40])
m > [15, 16, 35, 36]

In [ ]:
m < 25  ## equivalent to m < [25, 25, 25, 25]

In [ ]:
m[m < 25]

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("mean a = ", a.mean())

In [ ]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

In [21]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
c.sum(axis = 0) #sum across column

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [23]:
c.sum(axis = 1) #sum across row

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [24]:
c.sum(axis=(0,2)) #sum across row and columns

array([ 60,  92, 124])

In [25]:
0+1+2+3 + 12+13+14+15, 4+5+6+7 + 16+17+18+19, 8+9+10+11 + 20+21+22+23

(60, 92, 124)

In [26]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
np.square(a)

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]


array([[  6.25,   9.61,  49.  ],
       [100.  , 121.  , 144.  ]])

In [27]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

Original ndarray
[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 sign
[[-1.  1.  1.]
 [ 1.  1.  1.]]

 ceil
[[-2.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


C:\Users\Sushil\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """
C:\Users\Sushil\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log
  """


In [28]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
np.add(a, b)  # equivalent to a + b

array([ 3,  6,  2, 11])

In [29]:
np.greater(a, b)

array([False, False,  True, False])

In [30]:
np.maximum(a, b)

array([2, 8, 3, 7])

In [31]:
np.copysign(a, b)

array([ 1.,  2., -3.,  4.])

In [32]:
a = np.array([1, 5, 3, 19, 13, 7, 2])
a[3]

19

In [33]:
a[2:5]

array([ 3, 19, 13])

In [34]:
a[2:-1]

array([ 3, 19, 13,  7])

In [35]:
a[:2]

array([1, 5])

In [36]:
a[2::2]

array([ 3, 13,  2])

In [37]:
a[::-1]

array([ 2,  7, 13, 19,  3,  5,  1])

In [38]:
a[3]=999
a

array([  1,   5,   3, 999,  13,   7,   2])

In [39]:
a[2:5] = [997, 998, 999]
a

array([  1,   5, 997, 998, 999,   7,   2])

In [42]:
b = np.arange(48).reshape(4,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [43]:
b[1, 2]

14

In [44]:
b[1, :]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [46]:
b[: ,0]

array([ 0, 12, 24, 36])

In [47]:
b[1, :]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [48]:
b[1:2, :]

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [49]:
b[1:3, :]

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [50]:
b[0:2, 2:5]

array([[ 2,  3,  4],
       [14, 15, 16]])

In [51]:
b[(0,2), 2:5]

array([[ 2,  3,  4],
       [26, 27, 28]])

In [52]:
b[:, (-1, 2, -1)]

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

In [53]:
b[(-1, 2, -1, 2), (5, 9, 1, 9)]  # returns a 1D array with b[-1, 5], b[2, 9], b[-1, 1] and b[2, 9] (again)

array([41, 33, 37, 33])

In [55]:
c = b.reshape(4,2,6)
c

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [56]:
c[2, 1, 4]

34

In [57]:
c[2, :, 3]

array([27, 33])

In [58]:
c[2, 1]  # Return matrix 2, row 1, all columns.  This is equivalent to c[2, 1, :]

array([30, 31, 32, 33, 34, 35])

# ellips(...)

In [61]:
c[2, ...]  #  matrix 2, all rows, all columns.  This is equivalent to c[2, :, :]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [62]:
c[2, 0, ...] # matrix 2, row 1, all columns.  This is equivalent to c[2, 1, :]

array([24, 25, 26, 27, 28, 29])

In [63]:
c[2, ..., 3]  # matrix 2, all rows, column 3.  This is equivalent to c[2, :, 3]

array([27, 33])

In [64]:
c[..., 3] # all matrices, all rows, column 3.  This is equivalent to c[:, :, 3]

array([[ 3,  9],
       [15, 21],
       [27, 33],
       [39, 45]])

# Boolean indexing

In [65]:
d = np.arange(48).reshape(4,12)

In [66]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [67]:
row_on = np.array([True, False, True, False])
d[row_on, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [68]:
cols_on = np.array([False, True, False] * 4)
b[:, cols_on]  # All rows, columns 1, 4, 7 and 10

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

You cannot use boolean indexing this way on multiple axes, but you can work around this by using the ix_ function:



In [69]:
d[np.ix_(row_on, cols_on)]

array([[ 1,  4,  7, 10],
       [25, 28, 31, 34]])

In [70]:
np.ix_(row_on, cols_on)

(array([[0],
        [2]], dtype=int64), array([[ 1,  4,  7, 10]], dtype=int64))

In [73]:
d[d % 3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45])

# Iterating
Iterating over ndarrays is very similar to iterating over regular python arrays. Note that iterating over multidimensional arrays is done with respect to the first axis.

In [74]:
c = np.arange(24).reshape(2, 3, 4)  # A 3D array (composed of two 3x4 matrices)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [75]:
for m in c:
    print("item")
    print(m)

item
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
item
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [76]:
for i in range(len(c)):
    print("item")
    print(c[i])

item
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
item
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [79]:
len(c)
c.shape[0]

2

In [81]:
for i in c.flat:
    print("item", i)

item 0
item 1
item 2
item 3
item 4
item 5
item 6
item 7
item 8
item 9
item 10
item 11
item 12
item 13
item 14
item 15
item 16
item 17
item 18
item 19
item 20
item 21
item 22
item 23


# Stacking arrays
It is often useful to stack together different arrays. NumPy offers several functions to do just that. Let's start by creating a few arrays.

In [82]:
q1 = np.full((3,4), 1.0)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
q2 = np.full((3,4), 2.0)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [85]:
q3 = np.full((3,4), 3.0)


# vstack
Now let's stack them vertically using vstack:



In [86]:
q4 = np.vstack((q1, q2, q3))
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [89]:
q5 = np.hstack((q1, q3))  # We can also stack arrays horizontally using hstack:
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

# concatenate
The concatenate function stacks arrays along any given existing axis.

In [90]:
q7 = np.concatenate((q1, q2, q3), axis=0)  # Equivalent to vstack
q7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [91]:
q8 = np.stack((q1, q3))
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

# Splitting arrays
Splitting is the opposite of stacking. For example, let's use the vsplit function to split a matrix vertically.

First let's create a 6x4 matrix:

In [92]:
r = np.arange(24).reshape(6,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [93]:
r1, r2, r3 = np.vsplit(r, 3)
r1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [94]:
r2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
r3

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

There is also a `split` function which splits an array along any given axis. Calling `vsplit` is equivalent to calling `split` with `axis=0`. There is also an `hsplit` function, equivalent to calling `split` with `axis=1`:

In [96]:
r4, r5 = np.hsplit(r, 2)
r4

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [97]:
r5

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

# Transposing arrays
The `transpose` method creates a new view on an `ndarray`'s data, with axes permuted in the given order.

For example, let's create a 3D array:

In [98]:
t = np.arange(24).reshape(4,2,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

Now let's create an `ndarray` such that the axes `0, 1, 2` (depth, height, width) are re-ordered to `1, 2, 0` (depth→width, height→depth, width→height):

In [99]:
t1 = t.transpose((1,2,0))
t1

array([[[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20]],

       [[ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]]])

In [100]:
t1.shape

(2, 3, 4)

By default, `transpose` reverses the order of the dimensions:

In [101]:
t2 = t.transpose()  # equivalent to t.transpose((2, 1, 0))
t2

array([[[ 0,  6, 12, 18],
        [ 3,  9, 15, 21]],

       [[ 1,  7, 13, 19],
        [ 4, 10, 16, 22]],

       [[ 2,  8, 14, 20],
        [ 5, 11, 17, 23]]])

In [102]:
t2.shape

(3, 2, 4)

NumPy provides a convenience function `swapaxes` to swap two axes. For example, let's create a new view of `t` with depth and height swapped:

In [104]:
t3 = t.swapaxes(0,1)  # equivalent to t.transpose((1, 0, 2))
t3

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]])

In [105]:
t3.shape

(2, 4, 3)